// Code generated by protoc-gen-go. DO NOT EDIT.
// source: amazingchow/mapreduce/pb/mapreduce.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_ALIVE     WorkerStatus = 0
	WorkerStatus_WORKER_STATUS_UNHEALTHY WorkerStatus = 1
)

var WorkerStatus_name = map[int32]string{
	0: "WORKER_STATUS_ALIVE",
	1: "WORKER_STATUS_UNHEALTHY",
}

var WorkerStatus_value = map[string]int32{
	"WORKER_STATUS_ALIVE":     0,
	"WORKER_STATUS_UNHEALTHY": 1,
}

func (x WorkerStatus) String() string {
	return proto.EnumName(WorkerStatus_name, int32(x))
}

func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{0}
}

type Task struct {
	Inputs               []string `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetInputs() []string {
	if m != nil {
		return m.Inputs
	}
	return nil
}

type Worker struct {
	Id                   string       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               WorkerStatus `protobuf:"varint,5,opt,name=status,proto3,enum=amazingchow.mapreduce.WorkerStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{1}
}

func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Worker) GetStatus() WorkerStatus {
	if m != nil {
		return m.Status
	}
	return WorkerStatus_WORKER_STATUS_ALIVE
}

// ---------- request + response ----------
type AddTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{2}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type AddTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{3}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

type ListWorkersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWorkersRequest) Reset()         { *m = ListWorkersRequest{} }
func (m *ListWorkersRequest) String() string { return proto.CompactTextString(m) }
func (*ListWorkersRequest) ProtoMessage()    {}
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{4}
}

func (m *ListWorkersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkersRequest.Unmarshal(m, b)
}
func (m *ListWorkersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkersRequest.Marshal(b, m, deterministic)
}
func (m *ListWorkersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkersRequest.Merge(m, src)
}
func (m *ListWorkersRequest) XXX_Size() int {
	return xxx_messageInfo_ListWorkersRequest.Size(m)
}
func (m *ListWorkersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkersRequest proto.InternalMessageInfo

type ListWorkersResponse struct {
	Workers              []*Worker `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListWorkersResponse) Reset()         { *m = ListWorkersResponse{} }
func (m *ListWorkersResponse) String() string { return proto.CompactTextString(m) }
func (*ListWorkersResponse) ProtoMessage()    {}
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5cf3aee7a1e5ec0, []int{5}
}

func (m *ListWorkersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWorkersResponse.Unmarshal(m, b)
}
func (m *ListWorkersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWorkersResponse.Marshal(b, m, deterministic)
}
func (m *ListWorkersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWorkersResponse.Merge(m, src)
}
func (m *ListWorkersResponse) XXX_Size() int {
	return xxx_messageInfo_ListWorkersResponse.Size(m)
}
func (m *ListWorkersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWorkersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListWorkersResponse proto.InternalMessageInfo

func (m *ListWorkersResponse) GetWorkers() []*Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

func init() {
	proto.RegisterEnum("amazingchow.mapreduce.WorkerStatus", WorkerStatus_name, WorkerStatus_value)
	proto.RegisterType((*Task)(nil), "amazingchow.mapreduce.Task")
	proto.RegisterType((*Worker)(nil), "amazingchow.mapreduce.Worker")
	proto.RegisterType((*AddTaskRequest)(nil), "amazingchow.mapreduce.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "amazingchow.mapreduce.AddTaskResponse")
	proto.RegisterType((*ListWorkersRequest)(nil), "amazingchow.mapreduce.ListWorkersRequest")
	proto.RegisterType((*ListWorkersResponse)(nil), "amazingchow.mapreduce.ListWorkersResponse")
}

func init() {
	proto.RegisterFile("amazingchow/mapreduce/pb/mapreduce.proto", fileDescriptor_e5cf3aee7a1e5ec0)
}

var fileDescriptor_e5cf3aee7a1e5ec0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0xae, 0x93, 0x40,
	0x14, 0x76, 0xf0, 0xca, 0xf5, 0x1e, 0x14, 0xeb, 0x54, 0x2d, 0xb6, 0x6a, 0x08, 0x46, 0x83, 0x5d,
	0x40, 0xc4, 0x85, 0x89, 0xae, 0x30, 0x36, 0xa9, 0xb1, 0xd6, 0x04, 0xa8, 0x8d, 0x6e, 0x9a, 0x69,
	0x99, 0xe0, 0xa4, 0x96, 0x41, 0x66, 0x68, 0xa3, 0x4b, 0x5f, 0xc1, 0x47, 0xf3, 0x15, 0x7c, 0x0a,
	0x57, 0xa6, 0x80, 0xb5, 0xc4, 0x56, 0x5d, 0xce, 0x39, 0xdf, 0xcf, 0x7c, 0x5f, 0x0e, 0xd8, 0x64,
	0x45, 0x3e, 0xb3, 0x34, 0x59, 0xbc, 0xe7, 0x1b, 0x77, 0x45, 0xb2, 0x9c, 0xc6, 0xc5, 0x82, 0xba,
	0xd9, 0xfc, 0xf7, 0xc3, 0xc9, 0x72, 0x2e, 0x39, 0xbe, 0xbe, 0x87, 0x74, 0x76, 0xcb, 0xee, 0xad,
	0x84, 0xf3, 0xe4, 0x03, 0x75, 0x49, 0xc6, 0x5c, 0x92, 0xa6, 0x5c, 0x12, 0xc9, 0x78, 0x2a, 0x2a,
	0x92, 0x75, 0x07, 0x4e, 0x22, 0x22, 0x96, 0xf8, 0x06, 0xa8, 0x2c, 0xcd, 0x0a, 0x29, 0x0c, 0x64,
	0x9e, 0xb7, 0xcf, 0x82, 0xfa, 0x65, 0x4d, 0x40, 0x9d, 0xf2, 0x7c, 0x49, 0x73, 0xac, 0x83, 0xc2,
	0x62, 0x43, 0x31, 0x91, 0x7d, 0x16, 0x28, 0x2c, 0xc6, 0x4f, 0x41, 0x15, 0x92, 0xc8, 0x42, 0x18,
	0x17, 0x4c, 0x64, 0xeb, 0xde, 0x5d, 0xe7, 0xa0, 0xbf, 0x53, 0xd1, 0xc3, 0x12, 0x1a, 0xd4, 0x14,
	0xcb, 0x07, 0xdd, 0x8f, 0xe3, 0xad, 0x73, 0x40, 0x3f, 0x16, 0x54, 0x48, 0xec, 0xc2, 0x89, 0x24,
	0x62, 0x69, 0x20, 0x13, 0xd9, 0x9a, 0xd7, 0x3b, 0x22, 0x56, 0x32, 0x4a, 0xa0, 0x75, 0x15, 0xae,
	0xec, 0x24, 0x44, 0xc6, 0x53, 0x41, 0xad, 0x6b, 0x80, 0x47, 0x4c, 0xc8, 0xca, 0x51, 0xd4, 0xca,
	0xd6, 0x18, 0xda, 0x8d, 0x69, 0x05, 0xc6, 0x8f, 0xe1, 0x74, 0x53, 0x8d, 0xca, 0xc8, 0x9a, 0x77,
	0xfb, 0xaf, 0x01, 0x82, 0x5f, 0xe8, 0xfe, 0x73, 0xb8, 0xb4, 0x9f, 0x09, 0x77, 0xa0, 0x3d, 0x7d,
	0x1d, 0xbc, 0x1c, 0x04, 0xb3, 0x30, 0xf2, 0xa3, 0x49, 0x38, 0xf3, 0x47, 0x2f, 0xde, 0x0c, 0x5a,
	0xe7, 0x70, 0x0f, 0x3a, 0xcd, 0xc5, 0x64, 0x3c, 0x1c, 0xf8, 0xa3, 0x68, 0xf8, 0xb6, 0x85, 0xbc,
	0x1f, 0x08, 0xf4, 0x57, 0x24, 0x25, 0x09, 0xcd, 0x43, 0x9a, 0xaf, 0xd9, 0x82, 0xe2, 0x15, 0x9c,
	0xd6, 0x89, 0xf0, 0xbd, 0x23, 0x7f, 0x69, 0x96, 0xd6, 0xbd, 0xff, 0x2f, 0x58, 0x5d, 0x4c, 0xfb,
	0xcb, 0xb7, 0xef, 0x5f, 0x95, 0xcb, 0xd6, 0x45, 0x77, 0xfd, 0xd0, 0xdd, 0xb6, 0xf7, 0x04, 0xf5,
	0xf1, 0x27, 0xd0, 0xf6, 0x7a, 0xc1, 0x0f, 0x8e, 0x68, 0xfd, 0xd9, 0x68, 0xb7, 0xff, 0x3f, 0xd0,
	0xa6, 0x35, 0xd6, 0xb6, 0xd6, 0x75, 0x85, 0xcf, 0x7a, 0xef, 0x6e, 0x1e, 0x3e, 0x6b, 0x92, 0xb1,
	0xb9, 0x5a, 0x5e, 0xe6, 0xa3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x52, 0xf7, 0x29, 0xfa,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerServiceClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
}

type managerServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagerServiceClient(cc *grpc.ClientConn) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, "/amazingchow.mapreduce.ManagerService/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, "/amazingchow.mapreduce.ManagerService/ListWorkers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
type ManagerServiceServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
}

// UnimplementedManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServiceServer struct {
}

func (*UnimplementedManagerServiceServer) AddTask(ctx context.Context, req *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (*UnimplementedManagerServiceServer) ListWorkers(ctx context.Context, req *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkers not implemented")
}

func RegisterManagerServiceServer(s *grpc.Server, srv ManagerServiceServer) {
	s.RegisterService(&_ManagerService_serviceDesc, srv)
}

func _ManagerService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/amazingchow.mapreduce.ManagerService/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/amazingchow.mapreduce.ManagerService/ListWorkers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "amazingchow.mapreduce.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _ManagerService_AddTask_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _ManagerService_ListWorkers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amazingchow/mapreduce/pb/mapreduce.proto",
}
